inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'vendor/bundle/**/*'
   - 'Guardfile'
   - 'Gemfile'
   - 'Rakefile'
   - 'config/application.rb'
   - 'config/environments/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false
