inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
   - 'bin/*'
   - 'db/**/*'
   - 'vendor/bundle/**/*'
   - 'Guardfile'
   - 'Gemfile'
   - 'Rakefile'
   - 'config/application.rb'
   - 'config/environments/*'
   - 'spec/spec_helper.rb'
   - 'spec/rails_helper.rb'
   - 'features/support/env.rb'
   - 'lib/tasks/cucumber.rake'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AlignHash:
  Enabled: false
